SELECT COUNT(*) AS Positions
FROM employees
GROUP BY JOB_ID
ORDER BY Positions DESC;


SELECT AVG(SALARY) AS AVG_SALARY, COUNT(*) AS COUNT_EMPLOYEES
FROM employees
WHERE DEPARTMENT_ID="90";


SELECT JOB_ID, COUNT(*) AS COUNT_EMPLOYEES
FROM employees
GROUP BY JOB_ID
ORDER BY COUNT_EMPLOYEES DESC;


SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM employees;

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM employees
LEFT JOIN locations
-- за приєднання не впевнений, не зміг розгледіти ключове поле
ON DEPARTMENT_ID = LOCATION_ID
WHERE CITY="London";


